GithubApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'Github-App'

urlpatterns = [
	url(r'^$', views.repository, name='repository'),
	url(r'^index/$', views.repository, name='repository'),
	url(r'^repository/$', views.repository, name='repository'),
	url(r'^details/(?P<username>[A-z 0-9&-_+]+)/(?P<repository>.*)/(?P<sha>[A-z 0-9&.-_+]+)/', views.details, name='details'),
	url(r'^add/$', views.add, name='add'),
	url(r'^addall/$', views.addAllRepositories, name='addAllRepositories'),
	url(r'^clearall/$', views.clearAllRepositories, name='clearAllRepositories'),
	url(r'^downloadall/$', views.downloadAllRepositories, name='downloadAllRepositories'),
	url(r'^delete/$', views.delete, name='delete'),
	url(r'^authorize/$', views.authorize, name='authorize'),
]

Webtech3Opdracht/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('GithubApp.urls')),
    url(r'^GithubApp/', include('GithubApp.urls')),
]

GithubApp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

GithubApp/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect
from django.conf import settings
from django.shortcuts import render_to_response
from zipfile import ZipFile
from django.template import RequestContext
import os.path, json, urllib, urllib2, requests, re, logging, urlparse

githubRepoUrls = {}
userUrl = 'https://api.github.com/user'

def add(request):
	if (request.method == "POST" and request.POST):
		username = request.POST['username']
		repository = request.POST['repository']
		reposUrl = "https://api.github.com/repos/" + username + "/" + repository
		key = username + '/' + repository
		githubRepoUrls[key] = reposUrl
		print 'added ' + githubRepoUrls[key]
		if request.POST.get('download', False):
			downloadUrl =  "http://github.com/" + username + "/" + repository +  "/archive/master.zip"
			downloadedRepoPath = 'Repositories/' + username + '/' + repository  # users/naam/repo
			DownloadAndExtract(downloadUrl, downloadedRepoPath)
	  	return HttpResponseRedirect('/GithubApp/')
	else:
		return render(request, "GithubApp/addrepository.html", {})

def delete(request):
	k = request.POST.get('repokey', False)
	githubRepoUrls.pop(k, None)
	return HttpResponseRedirect("/GithubApp/")

def repository(request):
	commitsUrl = '' # e.g: https://api.github.com/repos/ErnstHarnie/Velo/commits
	userData = ''
	message = ''
	sessionKey = ''

	jsonReposData = {}
	jsonCommitsData = {}

	if 'access_token' in request.session:
		sessionKey = request.session['access_token']

	if githubRepoUrls:	 # if list is not empty
		for key in githubRepoUrls:
			reposUrl = githubRepoUrls[key]
			commitsUrl = githubRepoUrls[key] + "/commits" 
			downloadedRepoPath = 'Repositories/' + key
			print 'attempting to get ' + key

			jsonReposData[key] = GetData(reposUrl, sessionKey)
			jsonCommitsData[key] = GetData(commitsUrl, sessionKey)

			if 'message' in jsonReposData[key]:
				message = jsonReposData[key]['message']

	return render(request, "GithubApp/index.html", {'repos': jsonReposData, 'commit': jsonCommitsData, 'message': message})

def details(request, username, repository, sha):
	reposUrl = 'https://api.github.com/repos/' + username + "/" + repository
	commitsUrl = reposUrl + "/commits/" + sha
	message = ''
	lines = ''
	sessionKey = ''

	if 'access_token' in request.session:
		sessionKey = request.session.get('access_token')

	commitsData = GetData(commitsUrl, sessionKey)
	reposData = GetData(reposUrl, sessionKey)

	if 'message' in reposData:			# on error
		message = reposData['message']
		commitsData = ''
		reposData = ''

	if commitsData:
		lines = sorted(commitsData['files'], key=lambda c: c.get('changes', 0), reverse=True) # sorts files array from json
		maxElements = 10 
		del lines[:-maxElements] # deletes all elements after maxElements (10)

	return render(request, "GithubApp/details.html", {'commits': commitsData, 'sorted': lines,  'repos': reposData, 'message': message})

def addAllRepositories(request):
	if 'access_token' in request.session:
		repoUrl = userUrl + "/repos" 
		repoData = GetData(repoUrl, request.session['access_token'])

		for repo in repoData:
			reposUrl = "https://api.github.com/repos/" + repo['full_name']
			githubRepoUrls[repo['full_name']] = reposUrl

	return HttpResponseRedirect('/GithubApp/')

def downloadAllRepositories(request):
	message = ''
	if len(githubRepoUrls) > 0:
		repoUrl = userUrl + "/repos"

		for k, v in githubRepoUrls.iteritems():
			downloadUrl = "http://github.com/" + k + "/archive/master.zip"
			downloadedRepoPath = 'Repositories/' + k
			DownloadAndExtract(downloadUrl, downloadedRepoPath)
			message += k + ', '
		message += ' has been downloaded and extracted.'

	else:
		message = 'You need to add at least 1 repository.'

	return render(request, "GithubApp/downloadall.html", {'message': message})

def clearAllRepositories(request):
	githubRepoUrls.clear()
	return HttpResponseRedirect('/GithubApp/')

def authorize(request):
	message = ''
	if 'access_token' in request.session:
		message = 'You are authenticated already.'
	elif request.GET.get('code', ''):
		settings.CLIENT_CODE = request.GET.get('code', '')

		header = {'content-type':'application/json'} # required
		r = requests.post('https://github.com/login/oauth/access_token', data=json.dumps({'client_id':settings.CLIENT_ID, 'client_secret':settings.CLIENT_SECRET,'code':settings.CLIENT_CODE}), headers=header)
		if r.status_code is 200:
			parsed = urlparse.parse_qs(r.content)
			if 'access_token' in parsed:
				access_token = parsed['access_token'] 
				request.session['access_token'] = access_token[0]
				message = 'You have successfully been authenticated!'
			else:
				message = 'You cannot be authenticated. (' + str(parsed['error_description'][0]) + ')'
		else:
			message = 'You cannot be authenticated (' + str(r.status_code) + ').' 
	else:
		message = 'You cannot be authenticated.'
	return render(request, "GithubApp/authorize.html", {'message': message})

def DownloadAndExtract(url, destinationPath):
	#http://stackoverflow.com/questions/16760992/how-to-download-a-zip-file-from-a-site-python
	try:
		response = urllib.urlopen(url)
		zipFile = response.read()

		if not os.path.isdir(destinationPath):
			 os.makedirs(destinationPath)

		with open(destinationPath + "/master.zip", "wb") as f:
			f.write(zipFile)

		zf = ZipFile(destinationPath + "/master.zip")
		zf.extractall(path = destinationPath)
		zf.close()
	except Exception as e:
		print 'Unable to download and unzip: ' + str(e)

def GetData(url, token):
	try:
		response = ''
		data = ''
		logging.info('Attempting to get ' + url + ' with the following token: ' + token)

		if token: # if user is authenticated, add the token to header
			req = urllib2.Request(url)
			req.add_header('Authorization', 'token %s' % token)
			response = urllib2.urlopen(req).read() 
		else:
			response = urllib2.urlopen(url).read()

		data = json.loads(response.decode('utf-8'))
		print 'returned from ' + url

		return data
	except urllib2.HTTPError as h:
		print 'HTTPERROR: ' + str(h)
		if h.code == 403:
			response = '{"message": "You have reached the API limit. You need to authenticate, or wait until the next hour."}'
		elif h.code == 404:
			response = '{"message": "One or more repositories could not be found."}' 
		else:
			response = '{"message": "An error occured."}' 
		data = json.loads(response.decode('utf-8'))
		return data
	except Exception as e: 
		response = '{"message": "' + str(e) + '"}' 
		print 'Error when getting data: ' + str(e)
		data = json.loads(response.decode('utf-8'))
		return data

def DoesKeyExist(json, key):
	for result in json:
	    if key in result:
	        return True
	    else:
	    	return False

def DoesFileExist(path):
	if os.path.isfile(path):
		return True
	else:
		return False

GithubApp/templates/GithubApp/addrepository.html
{% extends 'GithubApp/base.html' %}
{% block body %}

<div class="container">
	<h1 class="col-sm-offset-2">Add a repository:</h1><br/>
	<form action="{% url 'Github-App:repository' %}" method="POST" class="form-horizontal" role="form">
		{% csrf_token %}
		<div class="form-group ">
			<label for="username" class="control-label col-sm-2">Username:</label>
			<div class="col-sm-10"> 
				<input type="text" name="username" id="username" required class="form-control"/>
			</div>
		</div>

		<div class="form-group">
			<label for="repository" class="control-label col-sm-2">Repository: </label>
			<div class="col-sm-10"> 
				<input type="text" name="repository" id="repository" required class="form-control" />
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-10">
				<div class="checkbox">
					<label><input type="checkbox" checked name="download" id="download" value="download">Download + extract repository</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"> Submit </button>
			</div>
		</div>
	</form>
</div>
{% endblock %}

GithubApp/templates/GithubApp/authorize.html
{% extends 'GithubApp/base.html' %}
{% block body %}

<div class="alert alert-info" role="alert">{{message}}</div>

<hr/>

{% endblock %}

GithubApp/templates/GithubApp/base.html
<html>

<head>
<link href="{{STATIC_URL|default:"/static/"}}css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'Github-App:repository' %}">Github App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav navbar-left">
        <li><a href="{% url 'Github-App:add' %}">Add</a></li>
        <li><a href="{% url 'Github-App:downloadAllRepositories' %}">Download + extract all repositories</a></li>
        <li><a href="{% url 'Github-App:clearAllRepositories' %}">Clear all repositories</a></li>

		</ul>
		<ul class="nav navbar-nav navbar-right">
    {% if not access_token %}
		<li><a href="https://github.com/login/oauth/authorize?client_id={{client_id}}">Authenticate</a></li> 
    {% elif user_data %}
    <li><a href="{% url 'Github-App:addAllRepositories' %}">Add all my repositories</a></li>
    <li><a href="#">Welcome {{user_data.login}}</a></li>
    {% endif %}
		</ul>
  </div><!-- /.container-fluid -->
</nav>

<div style="margin: 10px;">
{% block body %}
</div>
{% endblock %}
</body>

</html>

GithubApp/templates/GithubApp/details.html
{% extends 'GithubApp/base.html' %}
{% block body %}

{% if message %}
<div class="alert alert-info" role="alert">{{message}}</div>
{% endif %}

{% if repos %}

<h1 style="float:left;" class="pull-left">Details from <a href="http://www.github.com/{{repos.full_name}}" target="_blank">{{repos.full_name}}</a>: </h1>  <a href="http://github.com/{{repos.owner.login}}/{{repos.name}}/archive/{{repos.default_branch}}.zip" style="float:right;" class="btn btn-info" role="button" target="_blank">Download Repository ({{repos.default_branch}})</a> 
 <a href="http://github.com/{{repos.owner.login}}/{{repos.name}}/archive/{{commits.sha}}.zip" style="float:right;margin-right:5px;" class="btn btn-info" role="button" target="_blank">Download this commit</a>

<div class="container">
<table class="table">
<tr><th><strong>Commiter</strong></th><th>{{commits.commit.committer.name}}</th></tr>
<tr><th><strong>Date</strong></th><th>{{commits.commit.committer.date}}</th></tr>
<tr><th><strong>Message</strong></th><th>{{commits.commit.message}}</th></th></tr>
<tr><th><strong>Current commit</strong></th><th>{{commits.sha}}</th></tr>
<tr><th><strong>Total changes</strong></th><th>{{commits.stats.total}}</th></tr>
<tr><th><strong>Total additions</strong></th><th>{{commits.stats.additions}}</th></tr>
<tr><th><strong>Total deletions</strong></th><th>{{commits.stats.deletions}}</th></tr>
</table>
</div>

<h3>{{sorted|length}} Most changed files</h3>
<table class="table table-hover table-responsive">

<tr><th>Filename</th><th>Status</th><th>Total Changes</th><th>Additions</th><th>Deletions</th></tr>
{% for c in sorted %} 
<tr><td> {{c.filename}} </td> <td> {{c.status}} </td> <td> {{c.changes}}<td>{{c.additions}}</td></td><td>{{c.deletions}}</td> </tr>
{% endfor%}

</table>


{% else %}
<strong>Not found.</strong>
<p>Click <a href="{% url 'Github-App:add' %}">here</a> to add a repository.</p>
{% endif %}

{% endblock %}

GithubApp/templates/GithubApp/downloadall.html
{% extends 'GithubApp/base.html' %}
{% block body %}

<div class="alert alert-info" role="alert">{{message}}</div>

<hr/>

{% endblock %}

GithubApp/templates/GithubApp/index.html
{% extends 'GithubApp/base.html' %}
{% block body %}

{% if message %}
<div class="alert alert-info" role="alert">{{message}}</div>
{% endif %}

{% if repos %}
{% for k, r in repos.items %}
<form action="{%  url 'Github-App:delete' %}" method="POST" role="form">
{% csrf_token %}
<input type="text" id="repokey" name="repokey" value="{{k}}" hidden>
<button type="submit" style="float:right; margin:1px;" class="btn btn-danger"> Delete from list </button>
</form>
{% if r.full_name  %}
<h1 style="float:left;" class="pull-left">Commits from <a href="http://www.github.com/{{r.full_name}}" target="_blank">{{r.full_name}}</a>: </h1>  <a href="http://github.com/{{r.owner.login}}/{{r.name}}/archive/{{r.default_branch}}.zip" style="float:right;margin:1px" class="btn btn-info" role="button" target="_blank">Download Repository ({{r.default_branch}})</a>

<table class="table table-hover table-responsive">

{% if commit %}
<tr><th>Committed by</th><th>Message</th><th>Date</th><th>Download</th><th>Details</th></tr>

{% for key, commit in commit.items %} 
{% if k == key and not commit.message %}
{% for c in commit %}
<tr><td> {{c.commit.committer.name}} </td> <td> {{ c.commit.message }} </td> <td> {{ c.commit.committer.date }}<td><a href="http://github.com/{{r.owner.login}}/{{r.name}}/archive/{{c.sha}}.zip">Download</a></td></td><td><a href="{% url 'Github-App:details' r.owner.login r.name c.sha %}" target="_blank">Details</a></td> </tr>
{% endfor %}
</table>

{% elif k == key %}
</table>
<div class="alert alert-info" role="alert">No commits could be loaded. Perhaps this is an empty repository.</div>
{% endif %}


{% endfor %}
{% else %}
<p>No commits.</p>
{% endif %}

{% else %}
<p>Repository '{{k}}' could not be found.</p>
{% endif %}

<hr/>

{% endfor %}

{% else %}
<strong>No repositories added</strong>
<p>Click <a href="{% url 'Github-App:add' %}">here</a> to add a repository.</p>
{% endif %}

{% endblock %}